### ISSUE TITLE
Cv2 module

### ISSUE THREAD

**Issue by yougz11** [AdolfMacro/eyeRat#1]
![IMG_20220327_173523.jpg](https://user-images.githubusercontent.com/33231267/160289060-64c0081c-4244-4365-a098-c2882a3679cf.jpg)

Hello,
I dont understand, it seems like something is missing ? Can you help ?

**Comment by Hannes0084** [comment]
pip3 install opencv-python worked for me.

**Comment by AdolfMacro** [comment]
In the new version, the installer file will also be added.
For now, use the following command to fix your problem:
```
pip3 install opencv-python
```
