### ISSUE TITLE
Some ideas could help

### ISSUE THREAD

**Issue by abdou11ddq** [AdolfMacro/eyeRat#4]
please add the libraries to a .txt file
I suggest instead of printing [ ! ] Module pyaudio not found !
you could use subprocess to install it automatically with :
subprocess.run("pip3 install pyaudio", shell=True, check=True)

**Comment by AdolfMacro** [comment]
Hello, thanks for the feedback;
 I tried not to install anything automatically but if someone needs to install automatically they can run (**tools / installer.sh**)
